# Change these first
owner: ssfun # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SFUN BLOG
    url: https://sfun.cc
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: STATUS PAGE
    url: https://status.sfun.cc
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: PLEX SYNC
    url: $PLEXSYNC_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: EMBY KEEPER
    url: $EMBYKEEPER
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN RAYCAST
    url: $HF_SFUN_RAYCAST
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC RAYCAST
    url: $HF_SMGC_RAYCAST
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: WEWE RSS
    url: $WEWE_RSS_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: ARKOSE SOLVER
    url: $RENDER_ARKOSE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: ONEAPI SITE
    url: $ONEAPI_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN ONEAPI SITE 
    url: $HF_SFUN_ONEAPI_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC ONEAPI SITE 
    url: $HF_SMGC_ONEAPI_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN HFCHAT2API
    url: $HF_SFUN_HFCHAT2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC HFCHAT2API
    url: $HF_SMGC_HFCHAT2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN HFLLM2API
    url: $HF_SFUN_HFLLM2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC HFLLM2API
    url: $HF_SMGC_HFLLM2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN CHAT2API
    url: $HF_SFUN_CHAT2API
    __dangerous__body_down_if_text_missing: 'Gateway is disabled'
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
  - name: HF.SMGC CHAT2API
    url: $HF_SMGC_CHAT2API
    __dangerous__body_down_if_text_missing: 'Gateway is disabled'
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
  - name: HF.SFUN DUCK2API
    url: $HF_SFUN_DUCK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC DUCK2API
    url: $HF_SMGC_DUCK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: RENDER DUCK2API
    url: $RENDER_DUCK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: KOYEB DUCK2API
    url: $KOYEB_DUCK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SFUN DEEPSEEK2API
    url: $HF_SFUN_DEEPSEEK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HF.SMGC DEEPSEEK2API
    url: $HF_SMGC_DEEPSEEK2API
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sfun.cc
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ssfun/upptime/master/assets/upptime-icon.svg
  faviconSvg: https://raw.githubusercontent.com/ssfun/upptime/master/assets/upptime-icon.svg
  name: SFUN
  introTitle: "**SFUN's UPTIME SERVICE**"
  introMessage: This is an uptime monitor and status page for sfun's systems.
  navbar:
    - title: Uptime
      href: /
    - title: Status
      href: https://status.sfun.cc
    - title: Blog
      href: https://sfun.cc

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
