# Change these first
owner: ssfun # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SFUN BLOG
    url: https://sfun.cc
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: STATUS PAGE
    url: https://status.sfun.cc
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: PLEX SYNC
    url: $PLEXSYNC_SITE
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: Raycast Backend
    url: $RAYCAST_SITE
    expectedStatusCodes:
      - 401
    maxResponseTime: 5000
  - name: ONE API SITE 01
    url: $ONEAPI_SITE_01
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: ONE API SITE 02
    url: $ONEAPI_SITE_02
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HuggingChat API 01
    url: $HF_CHAT_01
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HuggingChat API 02
    url: $HF_CHAT_02
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HuggingFace API 01
    url: $HF_SPACE_01
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: HuggingFace API 02
    url: $HF_SPACE_02
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: GPTCHAT2API HF 01
    url: $HF_CHAT2API_01
    __dangerous__body_down_if_text_missing: '"detail": "Gateway is disabled"'
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
  - name: GPTCHAT2API HF 02
    url: $HF_CHAT2API_02
    __dangerous__body_down_if_text_missing: '"detail": "Gateway is disabled"'
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
  - name: GPTDUCK2API HF 01
    url: $HF_DUCK2API_01
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: GPTDUCK2API HF 02
    url: $HF_DUCK2API_02
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: GPT-3.5 API 01
    url: $GPT_RENDER
    expectedStatusCodes:
      - 200
      - 403
    maxResponseTime: 5000
  - name: GPT-3.5 API 02
    url: $GPT_KOYEB
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
  - name: SG CDN 01
    url: $SG_01
    port: 80
    check: "tcp-ping"
  - name: SG CDN 02
    url: $SG_02
    port: 80
    check: "tcp-ping"
  - name: JP CDN 01
    url: $JP_01
    port: 80
    check: "tcp-ping"
  - name: KR CDN 01
    url: $KR_01
    port: 80
    check: "tcp-ping"
  - name: US CDN 01
    url: $US_01
    port: 80
    check: "tcp-ping"
  - name: US CDN 02
    url: $US_02
    port: 80
    check: "tcp-ping"
  - name: AE CDN 01
    url: $AE_01
    port: 80
    check: "tcp-ping"
  - name: HK CDN 01
    url: $HK_01
    port: 80
    check: "tcp-ping"
  - name: HK CDN 02
    url: $HK_02
    port: 80
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sfun.cc
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ssfun/upptime/master/assets/upptime-icon.svg
  faviconSvg: https://raw.githubusercontent.com/ssfun/upptime/master/assets/upptime-icon.svg
  name: SFUN
  introTitle: "**SFUN's UPTIME SERVICE**"
  introMessage: This is an uptime monitor and status page for sfun's systems.
  navbar:
    - title: Uptime
      href: /
    - title: Status
      href: https://status.sfun.cc
    - title: Blog
      href: https://sfun.cc

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
